param (
    [string]$Title = "cTrader Report",
    [string]$Message = "",
    [string]$CsvPath = "",
    [string]$Token = "",
    [string]$ChatId = ""
)

$ErrorActionPreference = "Stop"

# Auto-load from telegram.env if exists
$envFile = Join-Path $PSScriptRoot "..\..\..\telegram.env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith("#")) {
            $parts = $line.Split("=", 2)
            if ($parts.Count -eq 2) {
                if ($parts[0].Trim() -eq "TELEGRAM_BOT_TOKEN") { $Token = $parts[1].Trim() }
                elseif ($parts[0].Trim() -eq "TELEGRAM_CHAT_ID") { $ChatId = $parts[1].Trim() }
            }
        }
    }
}

$uri = "https://api.telegram.org/bot" + $Token + "/sendMessage"

$fullText = "<b>" + $Title + "</b>`n`n"

if ($Message) {
    $fullText += $Message + "`n`n"
}

if ($CsvPath -and (Test-Path $CsvPath)) {
    $csvData = Import-Csv -Path $CsvPath | Select-Object -First 5
    $fullText += "<b>TOP RANKED RESULTS:</b>`n"
    foreach ($row in $csvData) {
        $props = $row | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name
        $lineStr = ""
        foreach ($p in $props) {
            $lineStr += "• " + $p + ": <b>" + $row.$p + "</b> "
        }
        $fullText += $lineStr + "`n"
    }
}

$fullText += "`n<i>Generated by Antigravity cTrader Agent</i>"

$payload = @{
    chat_id    = $ChatId
    text       = $fullText
    parse_mode = "HTML"
}

try {
    $response = Invoke-RestMethod -Uri $uri -Method Post -Body $payload
    if ($response.ok) {
        Write-Host "[TELEGRAM NOTIFIER SUCCESS] Report sent to Group ($ChatId)" -ForegroundColor Green
    } else {
        Write-Host "[TELEGRAM NOTIFIER ERROR] Failed to send" -ForegroundColor Red
    }
} catch {
    Write-Host "[TELEGRAM NOTIFIER EXCEPTION] $($_.Exception.Message)" -ForegroundColor Red
}
